server:
  port: 8089
  servlet:
    context-path: /library
spring:
  config:
    import: optional:configserver:http://localhost:8888/config
  datasource:
    url: jdbc:oracle:thin:@localhost:1521:/your-service-name
    username: username
    password: password
    driver-class-name: oracle.jdbc.OracleDriver
  jpa:
    hibernate:
      ddl-auto: none
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.OracleDialect
