server:
  port: 8088
  servlet:
    context-path: /student
spring:
  datasource:
    url: jdbc:oracle:thin:@//localhost:1521/your-service-name
    username: your_db_username
    password: your_db_password
    driver-class-name: oracle.jdbc.OracleDriver
  jpa:
    hibernate:
      ddl-auto: none # or update / validate / create-drop
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.OracleDialect
eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: http://localhost:8761/eureka
